version: '3.8'

services:
  client:
    build: .
    volumes:
      - "./client:/app"
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks: 
      - chat-network
    stdin_open: true

  server:
    build: .
    volumes:
      - "./server:/app"
    ports:
      - "5000:5000"
    networks: 
      - chat-network

networks: 
  chat-network:
    driver: bridge