version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chat-server-img
    ports: 
      - "5000:5000"
    networks: 
      - chat-network
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: chat-client-img
    depends_on: 
      - server
    ports: 
      - "3000:3000"
    networks: 
      - chat-network
    stdin_open: true
    
networks: 
  chat-network:
    driver: bridge



        